import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ThemeTogglerButton } from "@/components/animate-ui/components/buttons/theme-toggler";
import ClientSidebar from "@/components/animate-ui/components/platform/sidebar/clientSidebar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ClientSidebar>
          <ThemeTogglerButton className='absolute right-6 top-4 hover:cursor-pointer' />
        </ClientSidebar>

        {children}
      </body>
    </html>
  );
}
